enum Code {
  SUCCESS = 'SUCCESS',
  ER_NOT_FOUND = 'ER_NOT_FOUND',
  ER_COULD_NOT_BLOCK = 'ER_COULD_NOT_BLOCK',
  ER_COULD_NOT_DEACTIVATE = 'ER_COULD_NOT_DEACTIVATE',
  ER_COULD_NOT_CHANGE_STATE = 'ER_COULD_NOT_CHANGE_STATE',
  ER_COULD_NOT_ACTIVATE = 'ER_COULD_NOT_ACTIVATE',
  ER_LOGIN = 'ER_LOGIN',
  ER_EMAIL_EXISTS = 'ER_EMAIL_EXISTS',
  ER_EMAIL_FORMAT = 'ER_EMAIL_FORMAT',
  ER_LOGOUT = 'ER_LOGOUT',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  E_DATE_RANGE = 'E_DATE_RANGE',
}

export default Code
